### ISSUE TITLE
Octokit.ApiValidationException: Reference update failed

### ISSUE THREAD

**Issue by JanDeDobbeleer** [microsoft/winget-create#127]
# Brief description of your issue

Using `submit` fails with the latest self contained version

# Steps to reproduce

```pwsh
Invoke-WebRequest 'https://aka.ms/wingetcreate/latest/self-contained' -OutFile wingetcreate.exe
./wingetcreate.exe submit --token $Token $Version
```

# Expected behavior

It submits the PR successfully

# Actual behavior

```shell
Manifest validation succeeded: True

Submitting pull request for manifest...

Octokit.ApiValidationException: Reference update failed
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken)
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken)
   at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken)
   at Microsoft.WingetCreateCore.Common.GitHub.SubmitPRAsync(String packageId, String version, Dictionary`2 contents, Boolean submitToFork)
   at Microsoft.WingetCreateCore.Common.GitHub.SubmitPRAsync(String packageId, String version, Dictionary`2 contents, Boolean submitToFork)
   at Microsoft.WingetCreateCLI.Commands.BaseCommand.GitHubSubmitManifests(Manifests manifests, String token)
   at Microsoft.WingetCreateCLI.Commands.SubmitCommand.SubmitManifest()
   at Microsoft.WingetCreateCLI.Commands.SubmitCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
{"message":"Reference update failed","documentation_url":"https://docs.github.com/rest/reference/git#create-a-reference"}

Error: Process completed with exit code 1.
```

# Environment

GitHub actions Windows runner

**Comment by JanDeDobbeleer** [comment]
Seems to be resolved. Might have been an issue at GitHub.
