### ISSUE TITLE
Updating Nvidia.Broadcast results in YamlDotNet.Core.YamlException: (Line: 7, Col: 7, Idx: 209) - (Line: 7, Col: 17, Idx: 219): Exception during deserialization

### ISSUE THREAD

**Issue by banksio** [microsoft/winget-create#155]
# Brief description of your issue

# Steps to reproduce
Attempt to update the Nvidia Broadcast manifest using:
```
wingetcreate.exe update Nvidia.Broadcast --urls https://international.download.nvidia.com/Windows/broadcast/1.3.0/nvidia_broadcast_v1.3.0.45.exe
```

# Expected behavior
The manifest is updated.

# Actual behavior
WingetCreate crashes after `Retrieving latest manifest for Nvidia.Broadcast`, with the error:
```
YamlDotNet.Core.YamlException: (Line: 7, Col: 7, Idx: 209) - (Line: 7, Col: 17, Idx: 219): Exception during deserialization
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.CastInteger(UInt64 number, TypeCode typeCode)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.DeserializeIntegerHelper(TypeCode typeCode, String value)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.DeserializeHelper(Type tItem, IParser parser, Func`3 nestedObjectDeserializer, IList result, Boolean canUpdate)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Microsoft.WingetCreateCore.Serialization.DeserializeFromString[T](String value)
   at Microsoft.WingetCreateCore.Serialization.DeserializeManifestContents(IEnumerable`1 manifestContents)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.ExecuteManifestUpdate(List`1 latestManifestContent, CommandExecutedEvent commandEvent)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
```

# Environment
```
Windows Manifest Creator v0.3.0.6
```

**Comment by palenshus** [comment]
Looks like this is actually an issue with the schema, which defines this type as a plain integer, which when NJsonSchema compiles to c# turns into an int. If we change the schema to add `"format": "long"` (and `"minimum": 0"`), the resulting type will be able to hold all exit codes, which are of type uint.
