### ISSUE TITLE
wingetcreate can't create a reference when the forked repo has >= 254 branches

### ISSUE THREAD

**Issue by JanDeDobbeleer** [microsoft/winget-create#233]
### Brief description of your issue

wingetcreate (latest) can no longer create PR's successfully. The token which is used is still valid.
Looking at the error, my assumption is that [this](https://github.com/microsoft/winget-create/blob/10dc9bde27fa4dc2f7c231a2aace6ccbc6e876d3/src/WingetCreateCore/Common/GitHub.cs#L314) call fails.

```logs
Telemetry Settings
------------------
The Windows Package Manager Manifest Creator collects usage data in order to improve your experience.
The data is anonymous and collected only by Microsoft.
By default, telemetry is enabled but can be disabled by running `wingetcreate settings` and editing your settings file.

Manifest validation succeeded: True

Submitting pull request for manifest...

Octokit.NotFoundException: Not Found
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken)
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken)
   at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken)
   at Microsoft.WingetCreateCore.Common.GitHub.<>c__DisplayClass[19](https://github.com/JanDeDobbeleer/oh-my-posh/runs/5403344265?check_suite_focus=true#step:3:19)_0.<<SubmitPRAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int[32](https://github.com/JanDeDobbeleer/oh-my-posh/runs/5403344265?check_suite_focus=true#step:3:32) permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.WingetCreateCore.Common.GitHub.SubmitPRAsync(String packageId, String version, Dictionary`2 contents, Boolean submitToFork)
   at Microsoft.WingetCreateCore.Common.GitHub.SubmitPRAsync(String packageId, String version, Dictionary`2 contents, Boolean submitToFork)
   at Microsoft.WingetCreateCLI.Commands.BaseCommand.GitHubSubmitManifests(Manifests manifests)
   at Microsoft.WingetCreateCLI.Commands.SubmitCommand.SubmitManifest()
   at Microsoft.WingetCreateCLI.Commands.SubmitCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/git#create-a-reference"}

Error: Process completed with exit code 1.
```

### Steps to reproduce

```powershell
Invoke-WebRequest 'https://aka.ms/wingetcreate/latest/self-contained' -OutFile wingetcreate.exe
# Create the PR
./wingetcreate.exe submit --token $Token $Version
```

### Expected behavior

It creates a PR sucessfully

### Actual behavior

It errors

### Environment

```shell
GitHub Actions windows-latest
```

**Comment by JanDeDobbeleer** [comment]
I discovered what's causing the issue and a way to fix it, but not yet where exactly it then originates from. wingetcreate is unable to CREATE a reference when the forked repo has 254 branches. 

Possible causes:
- We validate if a branch was already created but do not paginate correctly and bail out somehow
- The GitHub API can't create a ref when this is the case.

I'll try to investigate a bit further, but my time is limited. But hey, I found the root cause :-)

**Comment by denelon** [comment]
@JanDeDobbeleer thanks for digging into this! I'll ask the team to investigate today and see if we can get more traction. I think I've got one other report that I just moved into this repository.

**Comment by ryfu-msft** [comment]
Thank you @JanDeDobbeleer for making my life easier :smile: I will work on adding an additional check for this and showing a friendly error message so that it is clearer as to what action the user should take to resolve this issue.

**Comment by JanDeDobbeleer** [comment]
@ryfu-msft do you know if it's related to this codebase/Oktokit or GitHub's API?

**Comment by ryfu-msft** [comment]
> @ryfu-msft do you know if it's related to this codebase/Oktokit or GitHub's API?

I believe this is related to GitHub's API. We simply call on the Octokit client to get the reference to the repository, which just invokes GitHub's REST API.

**Comment by JanDeDobbeleer** [comment]
@ryfu-msft that's indeed how I interpreted the code path. It's strange though. In my case the issue was resolved as soon as I deleted all remote autogenerated branches (and I then assumed that was the root cause), but that's not what people in #234 experience. Same error, different conditions. I'm actually really intrigued to debug this one.

**Comment by ryfu-msft** [comment]
@JanDeDobbeleer, I believe the issue is caused when your forked branch is behind the upstream reference "microsoft:master". 
Once I fetched the new commits and merged it into the fork's master branch, I was able to submit successfully. Could you try that and verify that it resolved the issue? If so, I'll need to work on adding functionality to have winget-create check that the fork's master branch is up to date before creating a reference.

**Comment by JanDeDobbeleer** [comment]
@ryfu-msft I actually did also reset my branch which fixed the issue. Will close this one, I think you're right.
