### ISSUE TITLE
Winget Create Error

### ISSUE THREAD

**Issue by gdiObjects** [microsoft/winget-create#234]
The following error message appeared when submitting an update to an existing package (gdiObjects.Perspective)
-----------
Manifest saved to C:\WINDOWS\system32\manifests\g\gdiObjects\Perspective\3.1.2203.2

Manifest validation succeeded: True

Submitting pull request for manifest...

Octokit.NotFoundException: Not Found
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 700
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 683
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 668
   at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 293
   at Microsoft.WingetCreateCore.Common.GitHub.<>c__DisplayClass19_0.<<SubmitPRAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.WingetCreateCore.Common.GitHub.SubmitPRAsync(String packageId, String version, Dictionary`2 contents, Boolean submitToFork)
   at Microsoft.WingetCreateCore.Common.GitHub.SubmitPRAsync(String packageId, String version, Dictionary`2 contents, Boolean submitToFork)
   at Microsoft.WingetCreateCLI.Commands.BaseCommand.GitHubSubmitManifests(Manifests manifests)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.ExecuteManifestUpdate(List`1 latestManifestContent, CommandExecutedEvent commandEvent)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/git#create-a-reference"}

**Comment by JanDeDobbeleer** [comment]
@gdiObjects in my case, I had too many branches on my winget-pkgs fork (254). As soon as I removed a few, everything started working again.

**Comment by gdiObjects** [comment]
> @gdiObjects in my case, I had too many branches on my winget-pkgs fork (254). As soon as I removed a few, everything started working again.

How do I remove branches from a winget-pkgs fork? (thanks)

**Comment by JanDeDobbeleer** [comment]
@gdiObjects you can use the GitHub UI to display all branches and there's a trash icon next to every one.

**Comment by gdiObjects** [comment]
> @gdiObjects you can use the [GitHub UI](https://github.com/gdiObjects/winget-pkgs/branches) to display all branches and there's a trash icon next to every one.

Thanks for the link!  There are only around 8 forks, so I'm not sure that's the problem.

**Comment by Megasware128** [comment]
I have the same error but I just have 1 branch still open

**Comment by ryfu-msft** [comment]
So I was able to repro the issue, and I believe the issue was that my forked branch was behind the upstream reference "microsoft:master". Once I fetched the new commits and merged it into the fork's master branch, I was able to submit successfully. Could you try that and verify that it resolved the issue?

**Comment by Megasware128** [comment]
@ryfu-msft Yes! Updating master on my fork fixed my issue

**Comment by r12f** [comment]
I am using the update command with --submit directly, and I am also getting this exact same error. The version I am using is v0.5.0.1.

```
.\wingetcreate.exe update r12f.Rnp -u https://github.com/r12f/rnp/releases/download/0.1.143.main/rnp.0.1.143.main.windows.x86.msix https://github.com/r12f/rnp/releases/download/0.1.143.main/rnp.0.1.143.main.windows.x64.msixhttps://github.com/r12f/rnp/releases/download/0.1.143.main/rnp.0.1.143.main.windows.arm64.msix -v 0.1.143.0 -t <PST> --submit
```

**Comment by slonopotamus** [comment]
I'm observing this issue even if I manually fetch changes from upstream to my fork of `winget-pkgs` repo before running winget-create =/
