### ISSUE TITLE
Unhandled exception on submitting pull request for manifest - part of winget-create new operation

### ISSUE THREAD

**Issue by dh2i-oj** [microsoft/winget-create#28]
As part of testing winget-create new, I'm trying to submit the manifest to the WIndows Package Manager repository and encountering the following error:

Submitting pull request for manifest...

Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatError()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.WingetCreateCLI.Logging.Logger.Log(LogLevel level, String format, Object[] args)
   at Microsoft.WingetCreateCLI.Logging.Logger.Error(String message, Object[] args)
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
   at Microsoft.WingetCreateCLI.Program.<Main>(String[] args)

**Comment by ryfu-msft** [comment]
Hi @dh2i-oj! Thanks for filing this bug. 

From the error message, it's hard for me to tell where the tool went wrong. Could you provide a screenshot or a list of what steps you took to get to this state? That way I can try it out and see what went wrong.

**Comment by dh2i-oj** [comment]
Hi Ryan,

Thanks for the email.

Just tried to reproduce the issue but it didn’t.  Previously, it would fail at the submitting the manifest to the Windows Package Manager repository. I’m not sure what changed this time to not reproduce the error.

Would you like to submit your manifest to the Windows Package Manager repository?: Yes
Using GitHub token from cache...
Submitting pull request for manifest...

Pull request can be found here: https://github.com/microsoft/winget-pkgs/pull/14107


Thanks again for looking into this issue.
