### ISSUE TITLE
Installer URIs being a redirect cause a `System.UnauthorizedAccessException`

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/winget-create#292]
### Brief description of your issue

When I supply an Installer URI that is a redirect to the actual download link, I get the `System.UnauthorizedAccessException` as shown below.

### Steps to reproduce

1. run `wingetcreate new`
1. Supply `https://www.two-notes.com/download/76391/` as installer url (it is the Windows / x64 installer from https://www.two-notes.com/en/torpedo-series/torpedo-remote/)

### Expected behavior

winget-create follows the redirect and downloads the installer from the correct path.

### Actual behavior

```
Downloading and parsing: https://www.two-notes.com/download/76391/...
Failed to download installer.
System.UnauthorizedAccessException: Access to the path 'C:\Users\HansBakker\AppData\Local\Temp\wingetcreate' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.WingetCreateCore.PackageParser.DownloadFileAsync(String url, Nullable`1 maxDownloadSize)
   at Microsoft.WingetCreateCLI.Commands.BaseCommand.DownloadPackageFile(String installerUrl)
   at Microsoft.WingetCreateCLI.Commands.NewCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
```
![image](https://user-images.githubusercontent.com/3463496/182043098-395aee81-6fca-4a7e-80f3-a601caa56896.png)

### Environment

```shell
Windows Package Manager v1.2.11601
Windows: Windows.Desktop v10.0.22000.795
Package: Microsoft.DesktopAppInstaller v1.17.11601.0
```

**Comment by Trenly** [comment]
For reference - the final destination url is `https://public-downloads.two-notes.com/setups/remote/Torpedo_Remote_5.4.14_x64_Setup.exe`
