### ISSUE TITLE
 Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by WardenHub** [microsoft/winget-create#306]
### Brief description of your issue

When I try to make a manifest I get the error  Exception has been thrown by the target of an invocation, see full errorstack below (Actual behavior)

This happens before I can input values.

### Steps to reproduce

wingetcreate.exe new "https://download.advanced-ip-scanner.com/download/files/Advanced_Port_Scanner_2.5.3869.exe"

### Expected behavior

Entering the prompted values

### Actual behavior

```

wingetcreate.exe new "https://download.advanced-ip-scanner.com/download/files/Advanced_Port_Scanner_2.5.3869.exe"
Downloading and parsing: https://download.advanced-ip-scanner.com/download/files/Advanced_Port_Scanner_2.5.3869.exe...

This tool will walk you through a series of questions to help you create your package manifest.

For information about the restrictions for each field, visit https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md

Press ENTER to submit the value for each question including accepting the (default) value.

Please enter values for the following fields:
The package unique identifier |e.g. Microsoft.VisualStudio|
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The handle is invalid.
   at System.ConsolePal.set_CursorVisible(Boolean value)
   at System.Console.set_CursorVisible(Boolean value)
   at Sharprompt.Drivers.DefaultConsoleDriver.Reset()
   at Sharprompt.Drivers.DefaultConsoleDriver.Dispose()
   at Sharprompt.Forms.FormRenderer.Dispose()
   at Sharprompt.Forms.FormBase`1.Dispose()
   at Sharprompt.Prompt.Input[T](InputOptions options)
   at Microsoft.WingetCreateCLI.PromptHelper.PromptValue[T](String message, Object model, String memberName, T instance)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.WingetCreateCLI.PromptHelper.PromptPropertyAndSetValue[T](Object model, String memberName, T instance, Int32 minimum, Object validationModel, String validationName
)
   at Microsoft.WingetCreateCLI.Commands.NewCommand.PromptPackageIdentifier(Manifests manifests)
   at Microsoft.WingetCreateCLI.Commands.NewCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
```

### Environment

```shell
Windows: Windows.Desktop v10.0.19043.1566
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0
```

**Comment by Trenly** [comment]
What version of wingetcreate are you using? Have you tried uninstalling and re-installing? 

![image](https://user-images.githubusercontent.com/12611259/193829285-46528c10-1710-424e-ab8e-b5cdb7d4fd7e.png)

**Comment by WardenHub** [comment]
Hey @Trenly , thank you for responding.

I'm using Version 1.1.2.0 installed via winget (how else! 👍 )

![image](https://user-images.githubusercontent.com/32770874/193839172-61640d84-47b6-4a16-ab1b-76526cf75c8e.png)

After uninstalling / re-installing I get the same error (nb. before I get the chance to enter values) 


```
Please enter values for the following fields:
The package unique identifier |e.g. Microsoft.VisualStudio|
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The handle is invalid.
   at System.ConsolePal.set_CursorVisible(Boolean value)
   at System.Console.set_CursorVisible(Boolean value)
   at Sharprompt.Drivers.DefaultConsoleDriver.Reset()
   at Sharprompt.Drivers.DefaultConsoleDriver.Dispose()
   at Sharprompt.Forms.FormRenderer.Dispose()
   at Sharprompt.Forms.FormBase`1.Dispose()
   at Sharprompt.Prompt.Input[T](InputOptions options)
   at Microsoft.WingetCreateCLI.PromptHelper.PromptValue[T](String message, Object model, String memberName, T instance)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.WingetCreateCLI.PromptHelper.PromptPropertyAndSetValue[T](Object model, String memberName, T instance, Int32 minimum, Object validationModel, String validationName)
   at Microsoft.WingetCreateCLI.Commands.NewCommand.PromptPackageIdentifier(Manifests manifests)
   at Microsoft.WingetCreateCLI.Commands.NewCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
```

**Comment by ryfu-msft** [comment]
Hey @WardenHub, 

The thrown IO exception is coming from [`System.Console.CursorVisible = true`](https://github.com/shibayan/Sharprompt/blob/2c5fcff2b81b9ac7a2769de4e501c4d0045acf89/Sharprompt/Drivers/DefaultConsoleDriver.cs#L61) which should rarely happen unless there is something corrupted with your console. I'm not sure if I can help with this but I would try restarting your computer or using different terminals to see if that changes anything. Sorry if that is not helpful but I don't think this is a bug that I can fix in our source code.

**Comment by ryfu-msft** [comment]
@WardenHub, 

I was able to repro your error when using powershell ISE. Looking into the prompting package that we use they specify their [supported platforms](https://github.com/shibayan/Sharprompt#supported-platforms) and Powershell ISE is not one of them. I will update the README to clarify this. Thanks for bringing this to our attention :) 

I will leave this issue open until I make the changes to the README.
