### ISSUE TITLE
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\runneradmin\AppData\Local\Temp\wingetcreate'.

### ISSUE THREAD

**Issue by JanDeDobbeleer** [microsoft/winget-create#453]
### Brief description of your issue

The executable exits with an error after successfully submitting a pull request when running in GitHub actions.

### Steps to reproduce

See the error [here](https://github.com/JanDeDobbeleer/aliae/actions/runs/6239672979/job/16938093059) and the way it's installed/used [here](https://github.com/JanDeDobbeleer/aliae/blob/main/packages/winget/build.ps1).

### Expected behavior

It doesn't exit with an error

### Actual behavior

```
Telemetry Settings
------------------
The Windows Package Manager Manifest Creator collects usage data in order to improve your experience.
The data is anonymous and collected only by Microsoft.
By default, telemetry is enabled but can be disabled by running `wingetcreate settings` and editing your settings file.

Manifest validation succeeded: True

Submitting pull request for manifest...

Pull request can be found here: https://github.com/microsoft/winget-pkgs/pull/120206

Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\runneradmin\AppData\Local\Temp\wingetcreate'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetFiles()
   at Microsoft.WingetCreateCLI.Common.CleanUpFilesOlderThan(String cleanUpDirectory, Int32 cleanUpDays)
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
   at Microsoft.WingetCreateCLI.Program.<Main>(String[] args)
```

### Environment

```shell
https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
```

**Comment by mdanish-kh** [comment]
Will be fixed by #452
