### ISSUE TITLE
`Octokit.ApiException` error when creating pull request

### ISSUE THREAD

**Issue by infinitepower18** [microsoft/winget-create#522]
### Brief description of your issue

When doing a `wingetcreate submit`, I got an `Octokit.ApiException` error and the forked repository said `This repository is temporarily unavailable. The backend storage is temporarily offline.` for a few minutes.

<img width="867" alt="image" src="https://github.com/microsoft/winget-create/assets/44692189/7b196d37-705f-4a1d-a18d-80720cdcec83">

### Steps to reproduce

Run `wingetcreate submit`

### Expected behavior

Successful pull request creation

### Actual behavior

API request error:

```
Octokit.ApiException: An error occurred with this API request
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 705
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 681
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 666
   at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 293
   at Microsoft.WingetCreateCore.Common.GitHub.<>c__DisplayClass19_0.<<SubmitPRAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.WingetCreateCore.Common.GitHub.SubmitPRAsync(String packageId, String version, Dictionary`2 contents, Boolean submitToFork, String prTitle, Boolean shouldReplace, String replaceVersion)
   at Microsoft.WingetCreateCore.Common.GitHub.SubmitPRAsync(String packageId, String version, Dictionary`2 contents, Boolean submitToFork, String prTitle, Boolean shouldReplace, String replaceVersion)
   at Microsoft.WingetCreateCLI.Commands.BaseCommand.GitHubSubmitManifests(Manifests manifests, String prTitle, Boolean shouldReplace, String replaceVersion)
   at Microsoft.WingetCreateCLI.Commands.SubmitCommand.SubmitManifest()
   at Microsoft.WingetCreateCLI.Commands.SubmitCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
```

### Environment

```shell
Windows Package Manager Manifest Creator v1.6.1.0
Copyright (c) Microsoft Corporation. All rights reserved.

Operating System: Microsoft Windows NT 10.0.22631.0
System Architecture: X64
```

**Comment by G0rocks** [comment]
I also got an error when submitting a pull request through `wingetcreate new` 

This is the error code:
`System.Net.Http.HttpRequestException: Response status code does not indicate success: 422 (Unprocessable Entity).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.WingetCreateCore.Common.GitHub.UpdateForkedRepoWithUpstreamCommits(Repository forkedRepo)
   at Microsoft.WingetCreateCore.Common.GitHub.<>c__DisplayClass20_0.<<SubmitPRAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.WingetCreateCore.Common.GitHub.SubmitPRAsync(String packageId, String version, Dictionary`2 contents, Boolean submitToFork, String prTitle, Boolean shouldReplace, String replaceVersion)
   at Microsoft.WingetCreateCore.Common.GitHub.SubmitPRAsync(String packageId, String version, Dictionary`2 contents, Boolean submitToFork, String prTitle, Boolean shouldReplace, String replaceVersion)
   at Microsoft.WingetCreateCLI.Commands.BaseCommand.GitHubSubmitManifests(Manifests manifests, String prTitle, Boolean shouldReplace, String replaceVersion)
   at Microsoft.WingetCreateCLI.Commands.NewCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)`

Here is my `wingetcreate info`
```
Copyright (c) Microsoft Corporation. All rights reserved.

Operating System: Microsoft Windows NT 10.0.19045.0
System Architecture: X64

Winget-Create Directories  Path
------------------------------------------------------------------------------------------------------------------------------------------
Logs                       %LOCALAPPDATA%\Packages\Microsoft.WindowsPackageManagerManifestCreator_8wekyb3d8bbwe\LocalState\DiagOutputDir
User settings              %LOCALAPPDATA%\Packages\Microsoft.WindowsPackageManagerManifestCreator_8wekyb3d8bbwe\LocalState\settings.json
Installer cache            %TEMP%\wingetcreate

Links
------------------------------------------------------------------
Privacy Statement    https://aka.ms/winget-create-privacy
License Agreement    https://aka.ms/winget-create-license
Third Party Notices  https://aka.ms/winget-create-3rdPartyNotice
Homepage             https://aka.ms/winget-create
```

And this is the package I was trying to add
https://github.com/imsnif/bandwhich/releases/download/v0.23.1/bandwhich-v0.23.1-x86_64-pc-windows-msvc.zip
From: https://github.com/imsnif/bandwhich/releases

**Comment by mdanish-kh** [comment]
@G0rocks That looks related to:

- https://github.com/microsoft/winget-create/issues/590

Could you manually sync your winget-pkgs fork & try again?

**Comment by G0rocks** [comment]
That worked thanks :)
Originally I thought you meant running `winget source update` which did not work xD
Thank you.

**Comment by W1BTR** [comment]
Could we get a note on here as to how we sync our winget-pkgs manually?

Cheers!

**Comment by mdanish-kh** [comment]
> Could we get a note on here as to how we sync our winget-pkgs manually?

https://github.com/microsoft/winget-create/issues/590#issuecomment-2769969934
