### ISSUE TITLE
update/new does not work when additional architecture are added for a package

### ISSUE THREAD

**Issue by nebula-it** [microsoft/winget-create#570]
### Brief description of your issue

`wingetcreate update/new` does not work when additional architecture are added for a package

### Steps to reproduce

Update
```
wingetcreate update --out $env:TEMP -t <token> https://github.com/siderolabs/talos/releases/download/v1.9.0/talosctl-windows-amd64.exe https://github.com/siderolabs/talos/releases/download/v1.9.0/talosctl-windows-arm64.exe
```
Fails with:
`Version https://github.com/siderolabs/talos/releases/download/v1.9.0/talosctl-windows-arm64.exe does not exist for https://github.com/siderolabs/talos/releases/download/v1.9.0/talosctl-windows-amd64.exe in the Windows Package Manager repository.`

New
```
wingetcreate new --out $env:TEMP -t <token> https://github.com/siderolabs/talos/releases/download/v1.9.0/talosctl-windows-amd64.exe https://github.com/siderolabs/talos/releases/download/v1.9.0/talosctl-windows-arm64.exe
```
Fails with:
`We have detected that this package identifier already exists. If you intend to update an existing package, please use the update command.`

### Expected behavior

Wingetcreate should update the manifest and add in the new architecture

### Actual behavior

Wingetcreate fails to update package

### Environment

```shell
Windows Package Manager Manifest Creator v1.9.2.0
```

**Comment by mdanish-kh** [comment]
Duplicate of #351;

See https://github.com/microsoft/winget-create/issues/351#issuecomment-1480294787

**Comment by nebula-it** [comment]
Thank you. Is there  a way to pass multiple installer URLs in that mode?
Running `wingetcreate update Sidero.talosctl --version 1.9.0 -t <token>   --interactive` only prompts me for one installer URL and if I select edit manifest files and then Installer File > Installers, it errors out with:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.WingetCreateCore.Common.Extensions.ToEnumAttributeValue(Enum enumVal)
   at Microsoft.WingetCreateCLI.PromptHelper.GenerateInstallerSelectionList(List`1 installers, Dictionary`2& installerSelectionMap)
   at Microsoft.WingetCreateCLI.PromptHelper.DisplayInstallersAsMenuSelection(InstallerManifest installerManifest)
   at Microsoft.WingetCreateCLI.PromptHelper.PromptPropertiesWithMenu[T](T model, String exitMenuWord, String modelName)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.DisplayManifestsAsMenuSelection(Manifests manifests)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.UpdateManifestsInteractively(Manifests manifests)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.ExecuteManifestUpdate(List`1 latestManifestContent, CommandExecutedEvent commandEvent)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
```
