### ISSUE TITLE
YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0)

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-create#90]
# Brief description of your issue /  Steps to reproduce /  Actual behavior

```
PS C:\Users\******\GitHub\winget-pkgs> wingetcreate update Balena.BalenaCLI -v 12.44.21 -u https://github.com/balena-io/balena-cli/releases/download/v12.44.21/balena-cli-v12.44.21-windows-x64-installer.exe -s
Retrieving latest manifest for Balena.BalenaCLI
YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 32, Idx: 31): Exception during deserialization
 ---> System.InvalidCastException: Invalid cast from 'System.String' to 'Microsoft.WingetCreateCore.Models.ManifestTypeBase'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType, CultureInfo culture)
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Microsoft.WingetCreateCore.Serialization.DeserializeFromString[T](String value)
   at Microsoft.WingetCreateCore.Serialization.DeserializeManifestContents(IEnumerable`1 manifestContents, Manifests manifests)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.DeserializeExistingManifestsAndUpdate(List`1 latestManifestContent)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.ExecuteManifestUpdate(List`1 latestManifestContent, CommandExecutedEvent commandEvent)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
```

# Expected behavior

Biip baap boop new manifest appears!

# Environment

>
```
Windows Manifest Creator v0.2.0.29
```

**Comment by palenshus** [comment]
Looks like manifest has a preceding BOM for some reason, and Octokit doesn't strip it out correctly
